integration_tests/e2e/createContacts.cy.ts
integration_tests/index.d.ts
integration_tests/mockApis/wiremock.ts
integration_tests/support/commands.ts
server/routes/contacts/create/enter-name/createContactEnterNameSchemas.ts

Assert that the create contact API is called with the correct parameters in the integration tests. While doing this I discovered a bug in that we were sending a title and middle name with an empty string instead of null.
Also added some missing tests to check that you can't just enter whitespace for the name.

PRC-56 : Add assertions to create contact integration tests

---

integration_tests/e2e/createContactsCheckAnswersChange.cy.ts
integration_tests/pages/createContactCheckYourAnswersPage.ts
integration_tests/pages/enterNamePage.ts
package-lock.json
package.json
server/@types/journeys/index.d.ts
server/routes/contacts/create/check-answers/createContactCheckAnswersController.test.ts
server/routes/contacts/create/check-answers/createContactCheckAnswersController.ts
server/routes/contacts/create/createContactMiddleware.test.ts
server/routes/contacts/create/enter-dob/createContactEnterDobController.test.ts
server/routes/contacts/create/enter-name/createContactEnterNameController.test.ts
server/routes/contacts/create/enter-name/createContactEnterNameController.ts
server/routes/contacts/create/start/startCreateContactJourneyController.test.ts
server/routes/contacts/create/start/startCreateContactJourneyController.ts
server/routes/contacts/manage/prisoner-search/prisonerSearchController.test.ts
server/routes/testutils/appSetup.ts
server/services/contactsService.test.ts
server/views/pages/contacts/create/checkAnswers.njk
server/views/pages/contacts/create/enterName.njk

Introduced flag to set once we are checking answers.  This is then used to redirect back to check answers straight from the enter name page. Also made it so the page is properly populated with either session data or form data if there was a validation error.

PRC-57: Support check answers update name flow

---

server/routes/contacts/create/createContactRoutes.ts
server/routes/contacts/manage/manageContactsRoutes.ts
server/routes/home/routes.ts
server/routes/index.ts

All controllers that return a promise (which is all of them currently) should be wrapped in asyncMiddleware. This is because if they return an unresolved error in a promise it causes node to crash... This means that any unhandled 400 or 500 from a dependency would result in a crash.

PRC-57: Wrap all controllers with asyncMiddleware

---

server/@types/journeys/index.d.ts
server/routes/contacts/create/check-answers/createContactCheckAnswersController.test.ts
server/routes/contacts/create/createContactMiddleware.test.ts
server/routes/contacts/create/createContactMiddleware.ts
server/routes/contacts/create/enter-dob/createContactEnterDobController.test.ts
server/routes/contacts/create/enter-name/createContactEnterNameController.test.ts
server/routes/contacts/create/start/startCreateContactJourneyController.test.ts
server/routes/contacts/create/start/startCreateContactJourneyController.ts
server/routes/contacts/manage/list/listContactsController.test.ts
server/routes/contacts/manage/manageContactsMiddleware.test.ts
server/routes/contacts/manage/manageContactsMiddleware.ts
server/routes/contacts/manage/prisoner-search/prisonerSearchController.test.ts
server/routes/contacts/manage/prisoner-search/prisonerSearchResultsController.test.ts
server/routes/contacts/manage/start/startManageContactsJourneyController.test.ts
server/routes/contacts/manage/start/startManageContactsJourneyController.ts
server/services/contactsService.test.ts

Dates aren't properly serialised in the session when it's persisted to redis so this can lead to issues when comparing the latest journeys. Converted to a string which is an ISO date instead and then create a Date where required.

PRC-57: Change lastTouched to be a date string in session

---

integration_tests/e2e/createContacts.cy.ts
integration_tests/e2e/createContactsCheckAnswersChange.cy.ts
integration_tests/pages/listContacts.ts
server/@types/contactsApi/index.d.ts
server/@types/journeys/index.d.ts
server/routes/contacts/create/check-answers/createContactCheckAnswersController.test.ts
server/routes/contacts/create/check-answers/createContactCheckAnswersController.ts
server/routes/contacts/create/createContactMiddleware.test.ts
server/routes/contacts/create/enter-dob/createContactEnterDobController.test.ts
server/routes/contacts/create/enter-estimated-dob/createContactEnterEstimatedDobController.test.ts
server/routes/contacts/create/enter-name/createContactEnterNameController.test.ts
server/routes/contacts/create/start/startCreateContactJourneyController.test.ts
server/routes/contacts/create/start/startCreateContactJourneyController.ts
server/services/contactsService.test.ts
server/services/contactsService.ts
server/views/pages/contacts/create/checkAnswers.njk
server/views/pages/contacts/create/enterDob.njk
server/views/pages/contacts/create/enterEstimatedDob.njk
server/views/pages/contacts/create/enterName.njk
server/views/pages/contacts/create/partials/createContactBreadcrumbs.njk
server/views/pages/contacts/manage/listContacts.njk

Added a return point to the "create contact" journey and updated the cancel buttons and breadcrumbs to use it.
Successfully creating a contact returns you to the prisoner contact list.
It is currently optional as a convenience for testing as you can currently only get to prisoner contact page by searching. The default is to cancel > home page and show the temporary success page.
Also sets the relationship with defaulted values for now so that the contact appears in the list.

PRC-55: link manage contacts and create new contact journeys

---

integration_tests/e2e/createContacts.cy.ts
integration_tests/e2e/createContactsCheckAnswersChange.cy.ts
server/@types/journeys/index.d.ts
server/middleware/prisonerDetailsMiddleware.test.ts
server/middleware/prisonerDetailsMiddleware.ts
server/routes/contacts/common/relationship/selectRelationshipController.test.ts
server/routes/contacts/create/check-answers/createContactCheckAnswersController.test.ts
server/routes/contacts/create/createContactRoutes.ts
server/routes/contacts/create/enter-dob/createContactEnterDobController.test.ts
server/routes/contacts/create/enter-estimated-dob/createContactEnterEstimatedDobController.test.ts
server/routes/contacts/create/enter-name/createContactEnterNameController.test.ts
server/routes/contacts/manage/contact-search/contactSearchController.test.ts
server/routes/contacts/manage/contact-search/contactSearchController.ts
server/routes/contacts/manage/list/listContactsController.test.ts
server/routes/contacts/manage/list/listContactsController.ts
server/routes/contacts/manage/manageContactsRoutes.ts
server/routes/index.ts
server/views/pages/contacts/common/partials/createContactBreadcrumbs.njk
server/views/pages/contacts/common/selectRelationship.njk
server/views/pages/contacts/create/checkAnswers.njk
server/views/pages/contacts/create/enterDob.njk
server/views/pages/contacts/create/enterEstimatedDob.njk
server/views/pages/contacts/create/enterName.njk
server/views/pages/contacts/manage/contactSearch.njk
server/views/pages/contacts/manage/listContacts.njk
server/views/partials/miniProfile/macro.njk
server/views/partials/miniProfile/template.njk

Move the loading of prisoner details to middleware to make it easier when it's only needed for mini profile.
Small changes to mini profile to make the import simpler.

PRC-109: Add mini profile to create flow

---

integration_tests/e2e/createContacts.cy.ts
integration_tests/e2e/createContactsCheckAnswersChangeOther.cy.ts
server/routes/contacts/common/emergency-contact/emergencyContactController.test.ts
server/routes/contacts/common/next-of-kin/nextOfKinController.test.ts
server/routes/contacts/create/enter-dob/createContactEnterDobController.test.ts
server/routes/contacts/create/enter-estimated-dob/createContactEnterEstimatedDobController.test.ts
server/utils/formatName.test.ts
server/utils/formatName.ts
server/utils/nunjucksSetup.ts
server/views/pages/contacts/common/partials/createContactBreadcrumbs.njk
server/views/pages/contacts/common/selectEmergencyContact.njk
server/views/pages/contacts/common/selectNextOfKin.njk
server/views/pages/contacts/common/selectRelationship.njk
server/views/pages/contacts/create/checkAnswers.njk
server/views/pages/contacts/create/enterDob.njk
server/views/pages/contacts/create/enterEstimatedDob.njk
server/views/pages/contacts/manage/contactSearch.njk
server/views/pages/contacts/manage/listContacts.njk
server/views/pages/contacts/manage/prisonerSearchResults.njk
server/views/partials/miniProfile/template.njk

Add a nunjucks filter for formatting objects with names to be used with prisoners and contacts. Prisoners currently do not show middle names while contacts do as per relevant tickets.
Capitalisation and middle names were missing from create journey so those have been fixed as a result.

PRC-53: Standardise formatting of name

---

integration_tests/e2e/addExistingContact.cy.ts
integration_tests/mockApis/contactsApi.ts
integration_tests/pages/searchContactPage.ts
server/@types/contactsApiClient/index.d.ts
server/@types/journeys/index.d.ts
server/data/contactsApiClient.test.ts
server/data/contactsApiClient.ts
server/routes/contacts/add/addContactFlowControl.test.ts
server/routes/contacts/add/addContactFlowControl.ts
server/routes/contacts/add/addContactRoutes.ts
server/routes/contacts/add/check-answers/createContactCheckAnswersController.test.ts
server/routes/contacts/add/emergency-contact/emergencyContactController.test.ts
server/routes/contacts/add/enter-dob/createContactEnterDobController.test.ts
server/routes/contacts/add/enter-estimated-dob/createContactEnterEstimatedDobController.test.ts
server/routes/contacts/add/enter-name/createContactEnterNameController.test.ts
server/routes/contacts/add/mode/addContactModeController.test.ts
server/routes/contacts/add/mode/addContactModeController.ts
server/routes/contacts/add/next-of-kin/nextOfKinController.test.ts
server/routes/contacts/add/relationship-comments/enterRelationshipCommentsController.test.ts
server/routes/contacts/add/relationship/selectRelationshipController.test.ts
server/services/contactsService.test.ts
server/services/contactsService.ts
server/views/pages/contacts/manage/contactSearch.njk

An initial version of the add existing contact flow re-using the pages from the create journey.  WIP cypress tests and known issues with the check answers page. Also does not actually call the add contact relationship API yet.

PRC-45: Link up existing contact flow

---

integration_tests/e2e/addExistingContact.cy.ts
integration_tests/e2e/createContacts.cy.ts
integration_tests/e2e/createContactsCheckAnswersChangeDob.cy.ts
integration_tests/e2e/createContactsCheckAnswersChangeOther.cy.ts
integration_tests/mockApis/contactsApi.ts
integration_tests/pages/createContactCheckYourAnswersPage.ts
server/data/contactsApiClient.test.ts
server/data/contactsApiClient.ts
server/routes/contacts/add/check-answers/createContactCheckAnswersController.test.ts
server/routes/contacts/add/check-answers/createContactCheckAnswersController.ts
server/services/contactsService.test.ts
server/services/contactsService.ts
server/views/pages/contacts/add/checkAnswers.njk

Existing contact flow now actually calls the API and hides the links on change answers for name and date of birth.

PRC-45: Link in existing contact API

---

assets/js/unbundled/relationshipHint.js
integration_tests/e2e/addExistingContact.cy.ts
integration_tests/e2e/addExistingContactCheckAnswers.cy.ts
integration_tests/e2e/createContacts.cy.ts
integration_tests/e2e/createContactsCheckAnswersChangeOther.cy.ts
integration_tests/pages/selectRelationshipPage.ts
server/routes/contacts/add/addContactFlowControl.test.ts
server/routes/contacts/add/addContactFlowControl.ts
server/routes/contacts/add/relationship/selectRelationshipController.test.ts
server/routes/contacts/add/relationship/selectRelationshipController.ts
server/routes/testutils/stubReferenceData.ts
server/views/pages/contacts/add/selectRelationship.njk

Add missing full stop to hint and default to a blank space so the continue button doesn't jump around.
Exclude NONE, ILP and OTHER from displaying the hint.
Sort options alphabetically.
Add back link to take to back to search results

PRC-48: Relationship page fixes

---

integration_tests/e2e/addExistingContact.cy.ts
integration_tests/e2e/addExistingContactCheckAnswers.cy.ts
integration_tests/e2e/contactConfirmationPage.cy.ts
integration_tests/e2e/searchContact.cy.ts
integration_tests/mockApis/contactsApi.ts
server/@types/contactsApi/index.d.ts
server/@types/contactsApiClient/index.d.ts
server/data/contactsApiClient.test.ts
server/data/contactsApiClient.ts
server/routes/contacts/manage/contact-confirmation/contactConfirmationController.test.ts
server/routes/contacts/manage/contact-search/contactSearchController.test.ts
server/routes/contacts/manage/contact-search/contactSearchController.ts
server/routes/testutils/testData.ts
server/services/contactsService.test.ts
server/services/contactsService.ts

Contact search now uses page types with contact search items.
Get contact by id and search contacts were using the same test util method but the types have drifted significantly so those have been split.

PRC-152: Re-import contacts types and fix test data factories

---

server/routes/contacts/add/mode/addContactModeController.test.ts
server/routes/contacts/add/mode/addContactModeController.ts

When switching from add existing to add new it was prefilling the name and date of birth. This could happen when you select "No" on contact confirmation and then click "The contact is not listed".
You could also proceed a new journey and relationship details would be persisted if you then went back to search results and chose existing contact.
Now the journey is reset whenever you select mode (click a result or not listed).

PRC-188: Reset journey on switch mode

---

integration_tests/e2e/addExistingContact.cy.ts
integration_tests/pages/createContactCheckYourAnswersPage.ts
server/@types/contactsApiClient/index.d.ts
server/@types/journeys/index.d.ts
server/data/contactsApiClient.test.ts
server/data/contactsApiClient.ts
server/routes/contacts/add/check-answers/createContactCheckAnswersController.test.ts
server/routes/contacts/add/mode/addContactModeController.test.ts
server/routes/contacts/add/mode/addContactModeController.ts
server/services/contactsService.test.ts
server/services/contactsService.ts
server/views/pages/contacts/add/checkAnswers.njk

If a contact is deceased we need to show the deceased date on check your answers when adding an existing contact to a prisoner.
Also, the types were wrong for get contact by id.

PRC-77: Show deceased date on CYA for existing contact

---

integration_tests/e2e/createContacts.cy.ts
server/routes/contacts/add/enter-dob/createContactEnterDobSchemas.test.ts
server/routes/contacts/add/enter-dob/createContactEnterDobSchemas.ts
server/views/pages/contacts/add/enterDob.njk
server/views/pages/contacts/add/selectEmergencyContact.njk
server/views/pages/contacts/add/selectNextOfKin.njk
server/views/pages/contacts/manage/contactSearch.njk
server/views/pages/contacts/manage/prisonerSearchResults.njk

Highlight the individual fields with errors
Show copy of the errors at both top and next to the field.
If no DOB fields entered at all, show a single message instead of individual field errors.
Also fixed highlighting on the search page as fields weren't being marked red.

PRC-56: Improve validation on DOB

---

server/routes/contacts/add/contact-confirmation/contactConfirmationController.test.ts
server/routes/testutils/testData.ts
server/views/pages/contacts/manage/contactConfirmation/identityNumbers.njk
server/views/pages/contacts/manage/contactDetails/manageIdentityNumbers.njk

display issuing authority only when it's provided on the summary pages for 'add' and  'manage' contact pages 
Test evidence : Manage
Test evidence : Add

PRC-213 : fix issuing authority 

---

server/views/pages/contacts/add/checkAnswers.njk
server/views/pages/contacts/add/selectEmergencyContact.njk
server/views/pages/contacts/add/selectNextOfKin.njk
server/views/pages/contacts/common/enterDob.njk
server/views/pages/contacts/common/enterEstimatedDob.njk
server/views/pages/contacts/common/enterName.njk
server/views/pages/contacts/common/enterRelationshipComments.njk
server/views/pages/contacts/common/selectRelationship.njk
server/views/pages/contacts/manage/addEditEmail.njk
server/views/pages/contacts/manage/addEditIdentity.njk
server/views/pages/contacts/manage/addEditPhone.njk
server/views/pages/contacts/manage/confirmDeleteEmail.njk
server/views/pages/contacts/manage/confirmDeleteIdentity.njk
server/views/pages/contacts/manage/confirmDeletePhone.njk
server/views/pages/contacts/manage/contactConfirmation/confirmation.njk
server/views/pages/contacts/manage/contactDetails/manageDomesticStatus.njk
server/views/pages/contacts/manage/contactDetails/manageEmergencyContactStatus.njk
server/views/pages/contacts/manage/contactDetails/manageGender.njk
server/views/pages/contacts/manage/contactDetails/manageInterpreter.njk
server/views/pages/contacts/manage/contactDetails/manageNextOfKinContactStatus.njk
server/views/pages/contacts/manage/contactDetails/manageSpokenLanguage.njk
server/views/pages/contacts/manage/contactSearch.njk
server/views/pages/contacts/manage/listContacts.njk
server/views/pages/contacts/manage/updateStaff.njk

Added the preventDoubleClick option to all buttons. This is an optional javascript feature with fallback to prevent double clicking submit buttons. I was able to reproduce issues fairly consistently by double clicking on create contact or email for example

PRC-330: Prevent double click

---

server/routes/contacts/manage/prisoner-search/prisonerSearchResultsController.test.ts
server/views/pages/contacts/manage/prisonerSearchResults.njk

Middle names were being shown in prisoner search results where they should never be shown for prisoners.

PRC-282: Hide offender middle names

---

integration_tests/e2e/addExistingContact.cy.ts
integration_tests/e2e/addExistingContactCheckAnswers.cy.ts
integration_tests/e2e/contactConfirmationPage.cy.ts
integration_tests/mockApis/contactsApi.ts
integration_tests/mockApis/wiremock.ts
integration_tests/pages/contactConfirmationPage.ts
server/@types/contactsApiClient/index.d.ts
server/data/contactsApiClient.ts
server/routes/contacts/add/contact-confirmation/contactConfirmationController.test.ts
server/routes/contacts/add/contact-confirmation/contactConfirmationController.ts
server/routes/testutils/testData.ts
server/services/contactsService.ts
server/utils/sortGlobalRestrictions.test.ts
server/utils/sortGlobalRstrictions.ts
server/views/pages/contacts/manage/contactConfirmation/confirmation.njk
server/views/pages/contacts/manage/contactConfirmation/restrictions.njk

Display the “Restrictions” tab of the Contact confirmation page, with global restrictions for a contact
**Restrictions sorted with dates**
**No restrictions**
**with more restrictions:**
**Expired title**

PRC-139 : Contact confirmation restrictions tab

---

integration_tests/e2e/createContactGlobalRestriction.cy.ts
integration_tests/e2e/createPrisonerContactRestriction.cy.ts
server/routes/contacts/add/success/successfullyAddedContactController.ts
server/routes/restrictions/check-answers/addRestrictionCheckAnswersController.test.ts
server/routes/restrictions/check-answers/addRestrictionCheckAnswersController.ts
server/routes/restrictions/enter-restriction/enterRestrictionController.test.ts
server/routes/restrictions/enter-restriction/enterRestrictionController.ts
server/routes/restrictions/success/successfullyAddedRestrictionController.test.ts
server/routes/restrictions/success/successfullyAddedRestrictionController.ts
server/views/pages/contacts/common/success.njk
server/views/pages/contacts/restrictions/addRestrictionCheckAnswers.njk
server/views/pages/contacts/restrictions/enterRestriction.njk

* Was sorting types incorrectly
* Hide contact name on enter restrictions page as it's in the question
* Re-format contact name & prisoner name hints to match design
* Hide prisoner name on success page
* Hide contact middle names throughout restrictions journey as per AC
* Delete journey on success (you could go back then create a 2nd restriction)
* Set focus to field selected in change link on CYA
* Always show cancel on CYA

PRC-74: Minor create restrictions tweaks

---

server/routes/contacts/add/contact-confirmation/contactConfirmationController.test.ts
server/routes/contacts/manage/addresses/manageAddressesController.test.ts
server/routes/contacts/manage/contact-details/contactDetailsController.test.ts
server/views/pages/contacts/common/addresses.njk
server/views/pages/contacts/common/notProvided.njk
server/views/pages/contacts/manage/address/addressMetadata.njk
server/views/pages/contacts/manage/contactConfirmation/addresses.njk
server/views/pages/contacts/manage/contactDetails/details.njk

Could not link a contact if they had an address with no address type.
Mail address question had wrong label.
Postcode was missing in several places addresses are rendered.
There was no way to add an address on a new contact as you only get the link to view all addresses if you have an address.  PRC-163 defined an add address link so adding it here.

PRC-163: Addresses fixes

---

integration_tests/e2e/addAddress.cy.ts
server/@types/prison-api.d.ts
server/routes/contacts/manage/addresses/use-prisoner-address/usePrisonerAddressController.test.ts
server/routes/contacts/manage/addresses/use-prisoner-address/usePrisonerAddressController.ts
server/services/prisonerAddressService.test.ts

Now prison API returns the codes so this updates the Prison API types and uses the codes for "use prisoner address" button.

PRC-321: Use town, county, country codes for use prisoner address

---

.circleci/config.yml
server/routes/prisonerImage/prisonerImageRoutes.ts

Turns out we needed additional config in circle to account for the different location of images during the build.
Hopefully this resolves - works in unit tests, int tests, running locally and in circle CI now.
*should* also work in DEV, PRE, PROD etc..

PRC-341: Prisoner image default location (esbuild has changed this)

---

server/routes/contacts/manage/addresses/manageAddressesController.test.ts
server/routes/contacts/manage/addresses/manageAddressesController.ts

Should be "[Home|Business|Work] address (expired)" or "Address (expired)".

PRC-165: Fix expired address label

---

server/utils/nunjucksSetup.ts
server/utils/utils.test.ts
server/utils/utils.ts
server/views/pages/contacts/manage/listContacts.njk

Some tests had started failing as date-fns rounds to the nearest year in minutes which doesn't work properly for age due to leap years. Changed to a custom implementation which diffs the years and then takes off one year if it hasn't been their birthday yet this year. If you were born on 29th Feb then your age doesn't tick up until 1st March on non-leap years which is safest for an under-18 check. Renamed function to reflect it's only used for age.

PRC-165: Fix age calculation

---

integration_tests/support/accessibilityViolations.ts
server/routes/contacts/add/emergency-contact/emergencyContactController.test.ts
server/routes/contacts/add/enter-dob/createContactEnterDobController.test.ts
server/routes/contacts/add/next-of-kin/nextOfKinController.test.ts
server/routes/contacts/add/relationship-type/relationshipTypeController.test.ts
server/routes/contacts/manage/addresses/address-type/addressTypeController.test.ts
server/routes/contacts/manage/relationship/manageEmergencyContactController.test.ts
server/routes/contacts/manage/relationship/manageNextOfKinContactController.test.ts
server/routes/contacts/manage/relationship/manageRelationshipStatusController.test.ts
server/routes/contacts/manage/update-dob/manageContactEnterDobController.test.ts
server/views/pages/contacts/add/relationshipType.njk
server/views/pages/contacts/add/selectEmergencyContact.njk
server/views/pages/contacts/add/selectNextOfKin.njk
server/views/pages/contacts/common/enterDob.njk
server/views/pages/contacts/manage/address/addressType.njk
server/views/pages/contacts/manage/contactDetails/manageEmergencyContactStatus.njk
server/views/pages/contacts/manage/contactDetails/manageGender.njk
server/views/pages/contacts/manage/contactDetails/manageInterpreter.njk
server/views/pages/contacts/manage/contactDetails/manageNextOfKinContactStatus.njk
server/views/pages/contacts/manage/contactDetails/manageRelationshipStatus.njk
server/views/pages/contacts/manage/updateApprovedToVisit.njk
server/views/pages/contacts/manage/updateStaff.njk

Questions with radio button answers that are also the H1 did not have an accessible legend. Moved the H1 to the fieldset for these questions as per GDS guidelines. Annoyingly, fieldset does not allow setting custom attributes so accessors in tests changed to class.

PRC-450: Add missing legends

---

integration_tests/e2e/deleteContactPhone.cy.ts
integration_tests/pages/confirmDeletePhonePage.ts
server/routes/contacts/manage/edit-contact-methods/editContactMethodsController.test.ts
server/routes/contacts/manage/edit-contact-methods/editContactMethodsController.ts
server/routes/contacts/manage/manageContactsRoutes.ts
server/routes/contacts/manage/name/changeTitleOrMiddleNamesController.test.ts
server/routes/contacts/manage/name/changeTitleOrMiddleNamesController.ts
server/routes/contacts/manage/phone/delete/manageContactDeletePhoneController.test.ts
server/routes/contacts/manage/phone/delete/manageContactDeletePhoneController.ts
server/routes/urls.ts
server/views/pages/contacts/manage/confirmDeletePhone.njk
server/views/pages/contacts/manage/contactDetails/details/contactMethodsTab.njk
server/views/pages/contacts/manage/contactDetails/details/editContactMethods.njk
server/views/partials/contactMethods/phoneNumbersCard.njk

Some minor text tweaks plus now returns directly to contact details on cancel or success. Made edit contact methods not require a return URL either.

PRC-279: Update delete contact phone

---

integration_tests/e2e/createContactIdentity.cy.ts
integration_tests/e2e/editContactIdentity.cy.ts
integration_tests/mockApis/contactsApi.ts
integration_tests/pages/changeIdentityDocumentPage.ts
server/data/contactsApiClient.ts
server/routes/contacts/manage/edit-contact-details/editContactDetailsController.test.ts
server/routes/contacts/manage/identities/IdentitySchemas.test.ts
server/routes/contacts/manage/identities/IdentitySchemas.ts
server/routes/contacts/manage/identities/add/manageContactAddIdentityController.test.ts
server/routes/contacts/manage/identities/add/manageContactAddIdentityController.ts
server/routes/contacts/manage/identities/edit/manageContactEditIdentityController.test.ts
server/routes/contacts/manage/identities/edit/manageContactEditIdentityController.ts
server/routes/contacts/manage/manageContactsRoutes.ts
server/routes/testutils/testData.ts
server/services/contactsService.ts
server/utils/utils.ts
server/views/pages/contacts/manage/editIdentity.njk
server/views/partials/contactDetails/identityDocumentationCard.njk

Updated design of edit identity documents. New errors, caption and heading plus re-order the fields.
Add identity document temporarily sharing the edit njk until next PR.

PRC-451: Edit identity documents

---

integration_tests/e2e/createContactIdentity.cy.ts
integration_tests/mockApis/contactsApi.ts
integration_tests/pages/addIdentityDocumentsPage.ts
package.json
server/@types/contactsApiClient/index.d.ts
server/data/contactsApiClient.test.ts
server/data/contactsApiClient.ts
server/middleware/validationMiddleware.ts
server/routes/contacts/manage/edit-contact-details/editContactDetailsController.test.ts
server/routes/contacts/manage/email/emailAddressesSchemas.test.ts
server/routes/contacts/manage/identities/IdentitySchemas.test.ts
server/routes/contacts/manage/identities/IdentitySchemas.ts
server/routes/contacts/manage/identities/add/manageContactAddIdentityController.test.ts
server/routes/contacts/manage/identities/add/manageContactAddIdentityController.ts
server/routes/contacts/manage/manageContactsRoutes.ts
server/services/contactsService.ts
server/views/pages/contacts/manage/addIdentities.njk
server/views/pages/contacts/manage/editIdentity.njk
server/views/partials/contactDetails/identityDocumentationCard.njk

Support for adding multiple identity documents at once. Initial implementation of add-another pattern.
Re-wrote the deduplication of error messages to support nested paths.
Error links are all correct and give focus to the correct field.
Complication in the controller to support different actions is only required when javascript is not enabled otherwise the adding/removing  of elements happens inline.

PRC-460: Add identity documents

---

integration_tests/e2e/createContactWithEmployments.cy.ts
server/routes/contacts/add/addContactFlowControl.test.ts
server/routes/contacts/add/addContactFlowControl.ts

Added some missing custom back link labels and restored the behaviour of back links on employments and address interstitial pages.
Also added a bunch of missing back link tests

PRC-553: Back link tweaks

---

server/data/contactsApiClient.ts
server/services/contactsService.test.ts
server/services/contactsService.ts
server/services/restrictionsService.test.ts
server/services/restrictionsService.ts

For potentially security related modifications we now include the details of the action in the audit event. This includes anywhere that sets isApprovedVisitor or adds or changes a restriction.
This would allow the audit team to see who approved or unapproved a visitor or set restrictions even if they have since been modified again.

PRC-615: Add audit event details for security

---

assets/scss/local.scss
server/views/pages/contacts/manage/employments/index.njk

Make sure the link doesn't wrap and has sufficient padding with long org names.

PRC-655: Delete employer link tweak

---

server/routes/contacts/add/success/successfullyAddedContactController.test.ts
server/views/pages/contacts/common/addedContactSuccessfully.njk

Links to the contact record and prisoner contact list have been added back for when it's a new contact only.
Existing contacts already provide links back to the contact information.

PRC-609: Add links on new contact success back

---

server/routes/contacts/add/success/successfullyAddedContactController.test.ts
server/views/pages/contacts/common/addedContactSuccessfully.njk

Remove the word "also" from the hint text when linking an existing contact as we do not show the restrictions content before so "also" doesn't make sense.

PRC-605: Tweak success page when not authoriser

---

integration_tests/e2e/listContactsAsAdmin.cy.ts
integration_tests/e2e/listContactsAsReadOnlyUser.cy.ts
integration_tests/mockApis/contactsApi.ts
integration_tests/pages/listContacts.ts
server/@types/contactsApi/index.d.ts
server/routes/contacts/manage/list/listContactsController.test.ts
server/routes/contacts/manage/list/listContactsController.ts

We recently discovered that a lot of the contacts added by prisons are inactive. This is due to how adding contacts from the visitor screen in NOMIS works and may not be intentional. It may be that the active flag is not really used in day-to-day operations.  Show all contacts by default to allow more research to take place.

PRC-735: Show inactive contacts by default

---

server/routes/contacts/manage/list/listContactsController.test.ts
server/views/pages/contacts/manage/listContacts.njk

Clear filters was resetting to active only specifically rather than the default and some wording when there were no results was no longer accurate.

PRC-735: UI tweaks/fixes now we show inactive by default

---

assets/scss/components/_header-bar.scss

For some reason there was a custom style imported from the template project that has a custom header for the phase banner.

PRC-649: Show border under phase banner

---

assets/scss/local.scss
server/routes/contacts/add/handle-duplicate/addContactHandleDuplicateController.test.ts
server/routes/contacts/manage/relationship/type/handle-duplicate/changeRelationshipTypeHandleDuplicateController.test.ts
server/views/pages/contacts/manage/contactDetails/relationship/handleDuplicateRelationship.njk

Now shows different label for continuing to the duplicate record when there is only one existing relationship.
Also further styling tweaks to the prisoner contact summary list.

PRC-787: Dupe protection screen fixes

---

integration_tests/e2e/manageRelationshipStatus.cy.ts
integration_tests/e2e/manageRelationshipStatusByAuthoriser.cy.ts
integration_tests/pages/contact-details/relationship/selectRelationshipStatusPage.ts
server/routes/contacts/manage/relationship/status/manageRelationshipStatusController.test.ts
server/routes/contacts/manage/relationship/status/manageRelationshipStatusController.ts
server/routes/testutils/appSetup.ts
server/utils/nunjucksSetup.ts
server/utils/permissionsUtils.test.ts
server/utils/permissionsUtils.ts
server/views/pages/contacts/manage/contactDetails/relationship/manageRelationshipStatus.njk

Add hint text guidance https://dsdmoj.atlassian.net/browse/PRC-821
Test evidence:
Authoriser
Administrator
Inactive relationship - no hint text
Active relationship - not approved to visit, no hint text

PRC-821 : add a hint text and guidance when changing the contact relationship status,

---

server/routes/contacts/add/check-answers/createContactCheckAnswersController.test.ts
server/routes/contacts/add/check-answers/createContactCheckAnswersController.ts
server/services/contactsService.ts
server/views/pages/contacts/add/new/checkAnswers.njk

for create new contact check-answer page,
1. skip date of birth row if it is for an internal contact
2. if dob is entered and then relationship is changed to an "internal contact" option, dob will still not be shown on CYA and not sent in API call

PRC-865 Skip dob on create new contact CYA page

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

Acceptance criteria
- On Monday **8th September**, HMP **Lewes** no longer has the alert banner on the prisoner contact list.
- On Monday **8th September**, HMP **Berwyn** no longer has the alert banner on the prisoner contact list.

PRC-911 : remove banner for Brewyn and Lewes

---

server/@types/contactsApiClient/index.d.ts
server/@types/journeys/index.d.ts
server/data/contactsApiClient.ts
server/routes/contacts/add/contact-search/contactSearchController.test.ts
server/routes/contacts/add/contact-search/contactSearchController.ts
server/routes/contacts/add/contact-search/contactSearchSchema.ts
server/views/pages/contacts/manage/contactSearch.njk

Acceptance criteria
The ‘normal’ search reverts back to the ‘normal’ search that is currently in Production
There exists a toggle ‘Sounds like’ toggle
When this is clicked, the current dev search applies to the search
The content matches the [Figma](https://www.figma.com/design/mfIjofNa89Pk9Ca0JmuXZS/Contacts-prototyping?node-id=6933-17973&t=o2HA7M4qhH2Q39hc-4)
Test evidence: shows the small text box

PRC-928 : add fuzzy search (#571)

---

server/routes/contacts/add/contact-match/contactMatchControllerAuthoriserRole.test.ts
server/routes/contacts/add/enter-name/createContactEnterNameController.test.ts
server/views/pages/contacts/add/existing/match.njk
server/views/pages/contacts/add/new/enterName.njk

AC:
1) On the Link a contact page, add a new warning text that says: As a Contacts Administrator, you cannot approve [contact] to visit [prisoner].  If you need to do this, ask for the Contacts Authoriser role.
2) On the first page of the add a new contact journey, add a warning text that reads: As a Contacts Administrator, you cannot approve this contact’s to visit [prisoner]. If you need to do this, ask for the Contacts Authoriser role.
3) Both messages are only shown to users who have the Contacts Administrator role and NOT the Contacts Authoriser role.
Test evidence : 
AC 1: 
AC2:

PRC-954 : Inform Contact Admins that they cannot approve a contact to visit
