ministryofjustice/hmpps-contacts-ui

helm_deploy/values-dev.yaml

fix dns host name issue

---

integration_tests/e2e/signIn.cy.ts
server/app.ts
server/enumeration/authorisedRoles.ts
server/routes/index.ts

**Ticket**: https://dsdmoj.atlassian.net/browse/PRC-16
**Description**: 
Application restricted to user with PRISON role
without `userRoles ['PRISON]`

PRC-16 Restrict Access To Role Prisoner User

---

assets/js/index.js
package-lock.json
package.json

**Ticket:** https://dsdmoj.atlassian.net/browse/PRC-23
**Description:** jQuery lib added to set up javascript for govuk and moj toolkit

PRC-23 - Add jQuery lib dependency

---

package-lock.json
package.json
server/app.ts
server/middleware/validationMiddleware.test.ts
server/middleware/validationMiddleware.ts
server/utils/nunjucksSetup.ts
server/views/partials/formErrorSummary.njk
server/views/partials/layout.njk

**Ticket:** https://dsdmoj.atlassian.net/browse/PRC-26
**Description:** 
- Validation middleware and zod for schema validation added in order to validate form fields and display error messages on the screen.
- zod validation schema package added to validate that data is strictly similar to data types user provides
Screenshot: (Sample page)

PRC-26 - Validation Middleware And Zod Package For Schema Validation Added

---

assets/scss/local.scss
integration_tests/e2e/contacts.cy.ts
integration_tests/e2e/signIn.cy.ts
integration_tests/pages/contacts.ts
integration_tests/pages/page.ts
integration_tests/pages/search.ts
server/@types/express/index.d.ts
server/app.ts
server/middleware/populateValidationErrors.ts
server/middleware/validationMiddleware.test.ts
server/middleware/validationMiddleware.ts
server/routes/contacts/controller.test.ts
server/routes/contacts/view.njk
server/routes/index.test.ts
server/routes/index.ts
server/routes/search/controller.test.ts
server/routes/search/controller.ts
server/routes/search/routes.ts
server/routes/search/schema.ts
server/routes/search/view.njk
server/routes/testutils/appSetup.ts
server/routes/urls.ts
server/utils/nunjucksSetup.ts

**Ticket**: https://dsdmoj.atlassian.net/browse/PRC-34
**Description**: Search prisoner form and validation
**Video**:
https://github.com/user-attachments/assets/b57e3236-505f-43e3-a4d9-8469049e089b

PRC-34 Create Search For A Prisoner Form Field And Validation

---

server/routes/contacts/view.njk
server/routes/search/view.njk
server/views/partials/formErrorSummary.njk
server/views/partials/layout.njk

**Ticket**: https://dsdmoj.atlassian.net/browse/PRC-44
**Description**: Top validation error has been moved below `Digital Prison Services > Contacts`
**Screenshot**:

PRC-44 Top Validation Error Moved Below Bredcrumb

---

helm_deploy/hmpps-contacts-ui/values.yaml
server/interfaces/pageHandler.ts
server/middleware/logPageViewMiddleware.ts
server/routes/contacts/controller.test.ts
server/routes/contacts/controller.ts
server/routes/contacts/routes.ts
server/routes/index.test.ts
server/routes/search/controller.test.ts
server/routes/search/controller.ts
server/routes/search/routes.ts
server/services/auditService.ts

[PRC-9](https://dsdmoj.atlassian.net/browse/PRC-9) : Audit queue integration
[PRC-9]: https://dsdmoj.atlassian.net/browse/PRC-9?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PRC-9 : Audit queue integration

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
server/data/restClient.test.ts
server/data/restClient.ts
tsconfig.json

This will resolve the deployment issue.

PRC-80: Add helm deploy required env vars and minor tidying updates.

---

integration_tests/pages/searchPrisoner.ts
server/@types/contactsApiClient/index.d.ts
server/data/contactsApiClient.ts
server/routes/contacts/contactRoutes.ts
server/routes/contacts/manage/list/listContactsController.test.ts
server/routes/contacts/manage/list/listContactsController.ts
server/routes/contacts/manage/manageContactsMiddleware.test.ts
server/routes/contacts/manage/manageContactsRoutes.ts
server/routes/contacts/manage/prisoner-search/prisonerSearchController.ts
server/routes/contacts/manage/prisoner-search/prisonerSearchResultsController.ts
server/routes/contacts/manage/start/startManageContactsJourneyController.test.ts
server/services/contactsService.ts
server/utils/utils.test.ts
server/utils/utils.ts
server/views/pages/contacts/manage/listContacts.njk
server/views/pages/contacts/manage/prisonerSearchResults.njk

PR with  a few things:
* Address peer review comments from previous PR
* Correcting breadcrumb links (with journey ID) - can traverse forward/backwards
* Adding service and API client methods to retrieve contact list
* Controller for list contacts (prisoner in context)
* Remove now unused functions
(the contacts list will be a series of PRs - not yet complete)

PRC-40: Initial work on list contacts + tidy-up

---

server/middleware/validationMiddleware.ts
server/routes/contacts/create/enter-name/createContactEnterNameSchemas.test.ts
server/routes/contacts/create/enter-name/createContactEnterNameSchemas.ts

Added special char and number validation on names with a dedicated validation test for enter name.

PRC-71 : Complete name validation

---

cypress.config.ts
integration_tests/e2e/createContacts.cy.ts
server/routes/contacts/create/enter-dob/createContactEnterDobSchemas.test.ts
server/routes/contacts/create/enter-dob/createContactEnterDobSchemas.ts

Ensure day, month and year and in valid ranges and that the date of birth is not in the future.

PRC-56 : Additional date of birth validation

---

integration_tests/pages/enterNamePage.ts
server/views/pages/contacts/create/enterName.njk

Updated design to latest with new labels and title on the page.

PRC-54 : Enter name tweaks

---

integration_tests/e2e/createContacts.cy.ts
integration_tests/e2e/createContactsCheckAnswersChange.cy.ts
integration_tests/pages/enterContactDateOfBirthPage.ts
integration_tests/pages/enterContactEstimatedDateOfBirthPage.ts
server/@types/journeys/index.d.ts
server/routes/contacts/create/check-answers/createContactCheckAnswersController.test.ts
server/routes/contacts/create/check-answers/createContactCheckAnswersController.ts
server/routes/contacts/create/enter-dob/createContactEnterDobController.test.ts
server/routes/contacts/create/enter-dob/createContactEnterDobController.ts
server/routes/contacts/create/enter-dob/createContactEnterDobSchemas.test.ts
server/routes/contacts/create/enter-dob/createContactEnterDobSchemas.ts
server/routes/contacts/create/enter-estimated-dob/createContactEnterDobController.test.ts
server/routes/contacts/create/enter-estimated-dob/createContactEnterEstimatedDobSchemas.ts
server/services/contactsService.test.ts
server/services/contactsService.ts
server/utils/formatYesNo.test.ts
server/utils/formatYesNo.ts
server/utils/nunjucksSetup.ts
server/views/pages/contacts/create/checkAnswers.njk
server/views/pages/contacts/create/enterDob.njk
server/views/pages/contacts/create/enterEstimatedDob.njk

Created a nunjucks filter to format yes, no, don't know answers. Standardised types with uppercase names.
Also convert "Do not know" to "I don't know" in line with acceptance criteria.

PRC-58: Standardise format of yes no don't know radios.

---

server/routes/contacts/manage/list/listContactsController.test.ts
server/views/pages/contacts/manage/listContacts.njk

Now shows 'Not provided' instead, as per the check answers page in create.

PRC-55: Contacts with no DOB blow up the list contacts page

---

integration_tests/e2e/createContacts.cy.ts
integration_tests/e2e/createContactsCheckAnswersChange.cy.ts
integration_tests/mockApis/contactsApi.ts
server/@types/contactsApi/index.d.ts
server/@types/contactsApiClient/index.d.ts
server/data/contactsApiClient.test.ts
server/data/contactsApiClient.ts
server/enumeration/referenceCodeType.ts
server/routes/contacts/create/createContactRoutes.ts
server/routes/contacts/create/enter-name/createContactEnterNameController.test.ts
server/routes/contacts/create/enter-name/createContactEnterNameController.ts
server/routes/index.ts
server/routes/testutils/stubReferenceData.ts
server/services/index.ts
server/services/referenceDataService.ts

Integrated the reference code API. Provide a dedicated service as we will be switching the source to different endpoints in the future. Set up stubbing mechanism for other reference data and integration tests.

PRC-107: Add reference data service and use for titles

---

integration_tests/mockApis/contactsApi.ts
server/routes/contacts/manage/contact-search/contactSearchController.test.ts
server/routes/contacts/manage/contact-search/contactSearchController.ts

**Ticket**: https://dsdmoj.atlassian.net/browse/PRC-46
**Description**: Page size set to 10 according to AC
**Screenshot**:

PRC-46 - Page Size Set To 10 For Contact Search

---

integration_tests/pages/searchContactPage.ts
server/routes/contacts/manage/contact-search/contactSearchController.test.ts
server/views/pages/contacts/manage/contactSearch.njk

**Ticket**: https://dsdmoj.atlassian.net/browse/PRC-151
**Description**: H1 title changed from '`Search for Contact`' to '`Search for a contact`' as per AC

PRC-151 H1 Title On Search Page Changed As Per AC

---

integration_tests/e2e/searchContact.cy.ts
server/routes/contacts/manage/contact-search/contactSearchController.ts
server/utils/utils.test.ts
server/utils/utils.ts

**Ticket**: https://dsdmoj.atlassian.net/browse/PRC-153
**Description**: Changes added on the util to fix the 400 error - surname and date with correct format for api when day or month starts with zero

PRC-153 - Fix date format for contact search api date of birth (eg. 1990-01-01)

---

integration_tests/e2e/searchContact.cy.ts
server/routes/contacts/manage/contact-search/contactSearchSchema.test.ts
server/routes/contacts/manage/contact-search/contactSearchSchema.ts

**Ticket**: https://dsdmoj.atlassian.net/browse/PRC-154
**Description**: 
isValid from date-fns package used to validate date of birth
- e.g. 30/02/1980
https://github.com/user-attachments/assets/32f9aac5-dcc4-41f3-924c-e80b511fc10c

PRC-154 - Fix invalid date of birth

---

integration_tests/e2e/createContacts.cy.ts
server/routes/contacts/add/enter-dob/createContactEnterDobSchemas.test.ts
server/routes/contacts/add/enter-dob/createContactEnterDobSchemas.ts

**Ticket**: https://dsdmoj.atlassian.net/browse/PRC-174
**Description**: Fix valid date on DOB screen for new contact
**Video:**
https://github.com/user-attachments/assets/752167c3-33f6-4b10-b8e4-69e8881243ba

PRC-174 - Validation added for a valid date

---

integration_tests/e2e/createContacts.cy.ts
integration_tests/e2e/searchContact.cy.ts
server/routes/contacts/add/enter-name/createContactEnterNameController.test.ts
server/routes/contacts/add/enter-name/createContactEnterNameController.ts
server/routes/contacts/add/enter-name/createContactEnterNameSchemas.test.ts
server/routes/contacts/add/enter-name/createContactEnterNameSchemas.ts
server/routes/contacts/manage/contact-search/contactSearchSchema.test.ts
server/routes/contacts/manage/contact-search/contactSearchSchema.ts

Small fixes to get contact name ready for peer review.
Change "middle name" to "middle names".
Sort title list alphabetically.

PRC-54: Contact name fixes

---

server/views/pages/contacts/add/enterDob.njk

Minor change to labels on new contact DOB

PRC-54: Enter DOB fixes

---

.circleci/config.yml

PRC-156 : Build the PREPROD and PROD environments

PRC-156 : Build the PREPROD and PROD environments 

---

.circleci/config.yml

PRC-156 : Enable deployment into pre and prod

PRC-156 : Enable deployment into pre and prod

---

integration_tests/e2e/createContacts.cy.ts
integration_tests/e2e/createContactsCheckAnswersChangeOther.cy.ts
server/routes/contacts/add/check-answers/createContactCheckAnswersController.test.ts
server/routes/contacts/add/check-answers/createContactCheckAnswersController.ts
server/views/pages/contacts/add/checkAnswers.njk

Show the full name including title.
Show Not provided if comments not entered.
Button should always be Create prisoner contact.

PRC-57: Small fixes to check answers for create contact

---

integration_tests/e2e/contactConfirmationPage.cy.ts
server/middleware/populateCurrentUser.ts
server/routes/contacts/add/addContactRoutes.ts
server/routes/contacts/add/check-answers/createContactCheckAnswersController.ts
server/routes/contacts/manage/contact-confirmation/contactConfirmationController.test.ts
server/routes/contacts/manage/contact-confirmation/contactConfirmationController.ts
server/utils/formatName.test.ts
server/utils/formatName.ts
server/utils/nunjucksSetup.ts
server/utils/utils.test.ts
server/utils/utils.ts
server/views/pages/contacts/manage/contactConfirmation/basicDetails.njk
server/views/pages/contacts/manage/contactConfirmation/confirmation.njk
server/views/pages/contacts/manage/contactSearch.njk
server/views/pages/contacts/manage/listContacts.njk
server/views/pages/contacts/manage/prisonerSearchResults.njk
server/views/pages/contacts/partials/addContactNavigation.njk

Also, display middle names wherever possible as per new guidelines. Only mini profile hides the middle names.
Also, fixed the DOB formatting on contact confirmation when it's not provided.

PRC-198: Fix name capitalisation

---

server/routes/contacts/add/enter-dob/createContactEnterDobController.test.ts
server/routes/contacts/add/enter-dob/createContactEnterDobController.ts

If you selected "No, I don't know it" for DOB and then from CYA answers go back to DOB and choose No again, then we lost the estimated DOB you pre-filled when we went to that screen.

PRC-57: Keep estimated DOB on CYA

---

server/views/pages/contacts/manage/contactDetails/manageBasicDetails.njk

Ticket: https://dsdmoj.atlassian.net/browse/PRC-222
Description: Card name renamed to '**Contact details**' for manage contact screen as per final design on [PRC-73](https://dsdmoj.atlassian.net/browse/PRC-73)
[PRC-73]: https://dsdmoj.atlassian.net/browse/PRC-73?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PRC-222 - Card title renamed as per design

---

server/routes/contacts/manage/contact-details/contactDetailsController.ts
server/utils/formatName.test.ts
server/utils/formatName.ts
server/utils/utils.test.ts
server/utils/utils.ts

**Ticket** : [PRC-227](https://dsdmoj.atlassian.net/browse/PRC-227)
**Description**: Additional filter added to format name as `title first mid last`
[PRC-227]: https://dsdmoj.atlassian.net/browse/PRC-227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PRC-227 - Reverse format name as Title First Mid Last method added

---

server/routes/contacts/manage/contact-details/contactDetailsContorller.test.ts
server/routes/testutils/testData.ts
server/views/pages/contacts/manage/contactDetails/details.njk
server/views/pages/contacts/manage/contactDetails/managePhoneNumbers.njk

Also fixed an issue with the type description on contact confirmation.

PRC-210: Show phone numbers on manage contact details page

---

server/routes/contacts/manage/staff/manageContactStaffController.test.ts
server/views/pages/contacts/manage/updateStaff.njk

PRC-169 : Manage contact staff status - fix back link

PRC-169 : Manage contact staff status - fix back link

---

server/@types/contactsApi/index.d.ts
server/routes/contacts/manage/list/listContactsController.test.ts
server/routes/testutils/testData.ts

Updated API types from swagger and adjusted test data for removed/added fields.

PRC-248: Update types and test data to match API changes for migration

---

integration_tests/e2e/createContactIdentity.cy.ts
integration_tests/e2e/deleteContactIdentity.cy.ts
integration_tests/e2e/editContactIdentity.cy.ts
server/routes/contacts/manage/contact-confirmation/contactConfirmationController.test.ts
server/routes/contacts/manage/contact-details/contactDetailsController.test.ts
server/routes/contacts/manage/identities/delete/manageContactDeleteIdentityController.test.ts
server/routes/contacts/manage/identities/edit/manageContactEditIdentityController.test.ts
server/routes/testutils/testData.ts
server/views/pages/contacts/manage/contactConfirmation/identityNumbers.njk
server/views/pages/contacts/manage/contactDetails/manageIdentityNumbers.njk

PRC-213- fix issuing authority 
- fix issuing authority for 'manage contact' and 'contact confirmation' pages(PRC-47)

PRC-213- fix issuing authority 

---

server/routes/contacts/manage/gender/contactGenderController.ts
server/views/pages/contacts/manage/addEditIdentity.njk
server/views/pages/contacts/manage/contactDetails/manageDomesticStatus.njk
server/views/pages/contacts/manage/contactDetails/manageGender.njk
server/views/pages/contacts/manage/contactDetails/manageInterpreter.njk
server/views/pages/contacts/manage/contactDetails/manageSpokenLanguage.njk
server/views/pages/contacts/manage/updateStaff.njk

Ticket: [PRC-303](https://dsdmoj.atlassian.net/browse/PRC-303)
Description: Capitalize as per design:
- Radio box labels
- Save and continue button label changed to Confirm and save
**BEFORE**:
**AFTER**:
[PRC-303]: https://dsdmoj.atlassian.net/browse/PRC-303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PRC-303 - Capitalize genders labels and Confirm and save button label added

---

integration_tests/e2e/deleteContactIdentity.cy.ts
integration_tests/pages/confirmDeleteIdentityPage.ts
server/routes/contacts/manage/identities/delete/manageContactDeleteIdentityController.test.ts
server/routes/contacts/manage/identities/delete/manageContactDeleteIdentityController.ts
server/routes/contacts/manage/manageContactsRoutes.ts
server/views/pages/contacts/manage/confirmDeleteIdentity.njk
server/views/pages/contacts/manage/contactDetails/manageNextOfKinContactStatus.njk

PRC-252: Confirm delete identity number

---

server/routes/contacts/add/success/successfullyAddedContactController.ts
server/views/pages/contacts/manage/listContacts.njk

Remove commented line and add missing no visit state on contact list links

PRC-306: Tidy up

---

integration_tests/e2e/addExistingContact.cy.ts
integration_tests/e2e/addExistingContactCheckAnswers.cy.ts
integration_tests/e2e/changeRelationship.cy.ts
integration_tests/e2e/manageEmergencyContact.cy.ts
integration_tests/e2e/manageNextOfKinContact.cy.ts
integration_tests/e2e/manageRelationshipComments.cy.ts
integration_tests/mockApis/contactsApi.ts
server/@types/contactsApi/index.d.ts
server/data/contactsApiClient.test.ts
server/data/contactsApiClient.ts
server/routes/contacts/manage/relationship/manageContactRelationshipController.test.ts
server/routes/contacts/manage/relationship/manageContactRelationshipController.ts
server/routes/contacts/manage/relationship/manageEmergencyContactController.test.ts
server/routes/contacts/manage/relationship/manageEmergencyContactController.ts
server/routes/contacts/manage/relationship/manageNextOfKinContactController.test.ts
server/routes/contacts/manage/relationship/manageNextOfKinContactController.ts
server/routes/contacts/manage/relationship/manageRelationshipCommentsController.test.ts
server/routes/contacts/manage/relationship/manageRelationshipCommentsController.ts
server/services/contactsService.test.ts
server/services/contactsService.ts

Also discovered that some manage relationship controllers were not returning to journey returnPoint url so fixed them.

PRC-328: Update prisoner-contact URLs

---

.circleci/config.yml

Change to our dev slack channel for alerts and releases.

PRC-187: Send notifications to dev slack channel

---

integration_tests/e2e/manageContacts.cy.ts
integration_tests/e2e/selectInterpreterNeeds.cy.ts
integration_tests/e2e/selectSpokenLanguage.cy.ts
integration_tests/mockApis/contactsApi.ts
server/data/contactsApiClient.test.ts
server/data/contactsApiClient.ts
server/enumeration/referenceCodeType.ts
server/routes/contacts/manage/manageContactsRoutes.ts
server/routes/contacts/manage/spoken-language/manageSpokenLanguageController.test.ts
server/routes/contacts/manage/spoken-language/manageSpokenLanguageController.ts
server/routes/testutils/stubReferenceData.ts
server/routes/testutils/testData.ts
server/services/contactsService.test.ts
server/services/contactsService.ts
server/views/pages/contacts/manage/contactDetails/manageSpokenLanguage.njk

PRC-334 : Tech - switch language to use reference_codes instead of custom language tables

PRC-334 : Tech - switch language to use reference_codes

---

assets/js/all.js
assets/js/autocomplete.js
assets/js/index.js
assets/js/utils.js
assets/scss/application.scss
assets/scss/components/_autocomplete.scss
integration_tests/e2e/addAddress.cy.ts
integration_tests/mockApis/contactsApi.ts
integration_tests/pages/enterAddressPage.ts
package-lock.json
package.json
server/@types/journeys/index.d.ts
server/enumeration/referenceCodeType.ts
server/routes/contacts/manage/addresses/enter-address/addressLinesSchemas.test.ts
server/routes/contacts/manage/addresses/enter-address/addressLinesSchemas.ts
server/routes/contacts/manage/addresses/enter-address/enterAddressController.test.ts
server/routes/contacts/manage/addresses/enter-address/enterAddressController.ts
server/routes/contacts/manage/manageContactsRoutes.ts
server/routes/testutils/stubReferenceData.ts
server/services/auditService.ts
server/views/pages/contacts/manage/address/enterAddress.njk
server/views/partials/layout.njk

Includes introduction of typeahead using accessible-autocomplete library. Client code lifted straight out of A&A

PRC-324: Address lines page

---

server/routes/contacts/manage/addresses/address-metadata/addressMetadataController.test.ts
server/routes/contacts/manage/addresses/address-metadata/addressMetadataController.ts
server/routes/contacts/manage/addresses/enter-address/enterAddressController.test.ts
server/routes/contacts/manage/addresses/enter-address/enterAddressController.ts
server/views/pages/contacts/manage/address/addressCheckAnswers.njk
server/views/pages/contacts/manage/address/addressMetadata.njk

Defaults to England and the current month/year when adding a new address.

PRC-324: Add default values for country and start date

---

integration_tests/e2e/createAddressPhone.cy.ts
integration_tests/e2e/deleteAddressPhone.cy.ts
integration_tests/e2e/editAddressPhone.cy.ts
integration_tests/mockApis/contactsApi.ts
server/@types/contactsApi/index.d.ts
server/@types/contactsApiClient/index.d.ts
server/data/contactsApiClient.test.ts
server/data/contactsApiClient.ts
server/routes/contacts/manage/addresses/manageAddressesController.test.ts
server/routes/contacts/manage/phone/delete-address-phone/manageContactDeleteAddressPhoneController.test.ts
server/routes/contacts/manage/phone/delete-address-phone/manageContactDeleteAddressPhoneController.ts
server/routes/contacts/manage/phone/edit-address-phone/manageContactEditAddressPhoneController.test.ts
server/routes/contacts/manage/phone/edit-address-phone/manageContactEditAddressPhoneController.ts
server/routes/testutils/testData.ts
server/services/contactsService.test.ts
server/utils/findMostRelevantAddressAndLabel.test.ts
server/views/pages/contacts/common/addresses.njk

Ids were mixed up and using contactPhoneId instead of contactAddressPhoneId.

PRC-351: Fix address phone pages

---

server/routes/contacts/manage/addresses/address-metadata/addressMetadataController.test.ts
server/routes/contacts/manage/addresses/address-metadata/addressMetadataController.ts
server/routes/contacts/manage/addresses/address-metadata/addressMetadataSchemas.test.ts
server/routes/contacts/manage/addresses/address-metadata/addressMetadataSchemas.ts
server/views/pages/contacts/manage/address/addressMetadata.njk

Show the address under the H1.
Validate the to date is on or after from date.

PRC-325: Address metadata page fixes

---

server/@types/contactsApi/index.d.ts
server/routes/testutils/testData.ts
server/views/partials/linkedPrisonerCard.njk

PRC-399 : Tech ticket - rename to relationship type description

PRC-399 : Tech ticket - rename to relationship type description

---

server/routes/contacts/add/addContactsUtils.test.ts
server/routes/contacts/add/addContactsUtils.ts
server/routes/contacts/add/check-answers/createContactCheckAnswersController.test.ts
server/routes/contacts/add/check-answers/createContactCheckAnswersController.ts
server/routes/contacts/add/emergency-contact/emergencyContactController.test.ts
server/routes/contacts/add/emergency-contact/emergencyContactController.ts
server/routes/contacts/add/enter-dob/createContactEnterDobController.test.ts
server/routes/contacts/add/enter-dob/createContactEnterDobController.ts
server/routes/contacts/add/enter-name/createContactEnterNameController.test.ts
server/routes/contacts/add/enter-name/createContactEnterNameController.ts
server/routes/contacts/add/next-of-kin/nextOfKinController.test.ts
server/routes/contacts/add/next-of-kin/nextOfKinController.ts
server/routes/contacts/add/relationship-comments/enterRelationshipCommentsController.test.ts
server/routes/contacts/add/relationship-comments/enterRelationshipCommentsController.ts
server/routes/contacts/add/relationship-to-prisoner/selectRelationshipToPrisonerController.test.ts
server/routes/contacts/add/relationship-to-prisoner/selectRelationshipToPrisonerController.ts
server/routes/contacts/add/relationship-type/relationshipTypeController.test.ts
server/routes/contacts/add/relationship-type/relationshipTypeController.ts
server/views/pages/contacts/add/checkAnswers.njk
server/views/pages/contacts/add/relationshipType.njk
server/views/pages/contacts/add/selectEmergencyContact.njk
server/views/pages/contacts/add/selectNextOfKin.njk
server/views/pages/contacts/common/enterDob.njk
server/views/pages/contacts/common/enterName.njk
server/views/pages/contacts/common/enterRelationshipComments.njk
server/views/pages/contacts/common/selectRelationship.njk
server/views/pages/contacts/manage/contactSearch.njk

Also fixed the widths as every standard form should be 2/3 widths.

PRC-233: Update captions in add journey

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
server/@types/journeys/index.d.ts
server/routes/contacts/manage/addresses/start/startAddressJourneyController.test.ts
server/routes/contacts/manage/addresses/start/startAddressJourneyController.ts

fix prometheus alert severity label

fix null address start date bug, and

---

.env.example
helm_deploy/values-dev.yaml

PRC-445 : UI pointing to personal relationships api for dev

PRC-445 : UI pointing to personal relationships api for dev

---

helm_deploy/values-prod.yaml

PRC-445 : Update UI project to point to personal-relationships-api for prod environment

PRC-445 : Update UI project to point to personal-relationships-api for prod environment

---

server/middleware/validationMiddleware.ts
server/routes/contacts/common/name/nameSchemas.test.ts
server/routes/contacts/common/name/nameSchemas.ts
server/views/partials/successNotificationBanner.njk

Now lists the actual chars that were invalid. Also removed the unnecessary style added to success banner.

PRC-264: Update error messages for invalid chars in name

---

server/@types/contactsApiClient/index.d.ts
server/@types/journeys/index.d.ts
server/data/contactsApiClient.ts
server/middleware/setUpSuccessNotificationBanner.ts
server/routes/contacts/manage/addresses/address-metadata/addressMetadataController.test.ts
server/routes/contacts/manage/addresses/address-metadata/addressMetadataController.ts
server/routes/contacts/manage/manageContactsRoutes.ts
server/routes/contacts/manage/update-employments/delete-employment/deleteEmploymentController.test.ts
server/routes/contacts/manage/update-employments/delete-employment/deleteEmploymentController.ts
server/routes/contacts/manage/update-employments/updateEmploymentsController.test.ts
server/routes/contacts/manage/update-employments/updateEmploymentsController.ts
server/routes/restrictions/update-restriction/updateRestrictionController.test.ts
server/routes/restrictions/update-restriction/updateRestrictionController.ts
server/services/contactsService.ts
server/views/pages/contacts/manage/updateEmployments/index.njk

PRC-259 Patch contact employments with success notification

---

server/routes/contacts/manage/name/changeTitleOrMiddleNamesController.test.ts
server/views/pages/contacts/manage/changeTitleOrMiddleNames.njk

Button label was wrong and first and last name should be capitalised

PRC-264: Fixes for title and middle name

---

integration_tests/e2e/selectGender.cy.ts
integration_tests/pages/selectGenderPage.ts
server/routes/contacts/manage/edit-contact-details/editContactDetailsController.test.ts
server/routes/contacts/manage/gender/contactGenderController.test.ts
server/routes/contacts/manage/gender/contactGenderController.ts
server/routes/contacts/manage/gender/contactGenderSchema.ts
server/routes/contacts/manage/manageContactsRoutes.ts
server/views/pages/contacts/manage/contactDetails/manageGender.njk
server/views/partials/contactDetails/personalInformationCard.njk

PRC-265 Contact details-Edit gender

---

integration_tests/e2e/changeContactDateOfBirth.cy.ts
integration_tests/pages/contact-details/dobPage.ts
integration_tests/pages/editContactDetailsPage.ts
server/routes/contacts/common/enter-dob/enterDobSchemas.ts
server/routes/contacts/manage/edit-contact-details/editContactDetailsController.test.ts
server/routes/contacts/manage/manageContactsRoutes.ts
server/routes/contacts/manage/update-dob/manageContactDobSchema.ts
server/routes/contacts/manage/update-dob/manageContactEnterDobController.test.ts
server/routes/contacts/manage/update-dob/manageContactEnterDobController.ts
server/views/pages/contacts/manage/contactDetails/manageDob.njk
server/views/partials/contactDetails/personalInformationCard.njk

PRC-275 edit contact details - dob page

---

integration_tests/e2e/deleteContactEmail.cy.ts
integration_tests/pages/confirmDeleteEmailPage.ts
server/routes/contacts/manage/email/delete/manageContactDeleteEmailController.test.ts
server/routes/contacts/manage/email/delete/manageContactDeleteEmailController.ts
server/views/pages/contacts/manage/confirmDeleteEmail.njk

PRC-280 delete contact email page

---

integration_tests/e2e/deleteContactIdentity.cy.ts
integration_tests/pages/contact-details/confirmDeleteIdentityPage.ts
server/routes/contacts/manage/edit-contact-details/editContactDetailsController.test.ts
server/routes/contacts/manage/identities/delete/manageContactDeleteIdentityController.test.ts
server/routes/contacts/manage/identities/delete/manageContactDeleteIdentityController.ts
server/routes/contacts/manage/manageContactsRoutes.ts
server/views/pages/contacts/manage/confirmDeleteIdentity.njk
server/views/pages/contacts/manage/contactDetails/details/editContactDetails.njk
server/views/partials/contactDetails/identityDocumentationCard.njk

PRC-461
https://files.slack.com/files-pri/T01066BNN9G-F08FMC3J1PS/image.png

PRC-461 delete id document page

---

server/routes/contacts/manage/addresses/primary-or-postal/addressFlagsController.test.ts

PRC-470 unit tests for address flags page

---

server/routes/contacts/manage/addresses/comments/addressCommentsController.test.ts
server/routes/contacts/manage/addresses/comments/addressCommentsSchema.ts

PRC-493 enter address comments page

---

integration_tests/e2e/createEmail.cy.ts
integration_tests/mockApis/contactsApi.ts
integration_tests/pages/addEmailsPage.ts
server/data/contactsApiClient.test.ts
server/data/contactsApiClient.ts
server/routes/contacts/manage/email/add/manageContactAddEmailController.test.ts
server/routes/contacts/manage/email/add/manageContactAddEmailController.ts
server/routes/contacts/manage/email/emailSchemas.test.ts
server/routes/contacts/manage/email/emailSchemas.ts
server/routes/contacts/manage/manageContactsRoutes.ts
server/services/contactsService.test.ts
server/services/contactsService.ts
server/views/pages/contacts/manage/contactMethods/addEmails.njk

Add support for adding multiple email addresses at once.

PRC-465: Add multiple emails

---

integration_tests/e2e/createContactPhone.cy.ts
integration_tests/mockApis/contactsApi.ts
integration_tests/pages/contact-methods/addPhonesPage.ts
server/data/contactsApiClient.ts
server/routes/contacts/manage/addresses/add-address-phone/manageContactAddAddressPhoneController.test.ts
server/routes/contacts/manage/manageContactsRoutes.ts
server/routes/contacts/manage/phone/add/manageContactAddPhoneController.test.ts
server/routes/contacts/manage/phone/add/manageContactAddPhoneController.ts
server/services/contactsService.ts
server/views/pages/contacts/manage/contactMethods/addPhone.njk

PRC-464 add contact phone page

---

integration_tests/e2e/addAddress.cy.ts
integration_tests/e2e/createAddressPhone.cy.ts
integration_tests/pages/contact-methods/address/phone/addAddressPhonesPage.ts
server/@types/journeys/index.d.ts
server/routes/contacts/manage/addresses/add-address-phone/AddAddressPhonesSchema.ts
server/routes/contacts/manage/addresses/add-address-phone/addressPhoneController.test.ts
server/routes/contacts/manage/addresses/add-address-phone/addressPhoneController.ts
server/routes/contacts/manage/addresses/add-address-phone/manageContactAddAddressPhoneController.ts
server/routes/contacts/manage/addresses/comments/addressCommentsController.test.ts
server/routes/contacts/manage/addresses/comments/addressCommentsController.ts
server/routes/contacts/manage/addresses/primary-or-postal/addressFlagsController.test.ts
server/routes/contacts/manage/addresses/primary-or-postal/addressFlagsController.ts
server/routes/contacts/manage/manageContactsRoutes.ts

PRC-468 Add enter phone numbers page to Add address journey

---

integration_tests/e2e/addExistingContact.cy.ts
integration_tests/e2e/createContacts.cy.ts
integration_tests/pages/addContactSuccessPage.ts
integration_tests/pages/createContactSuccessPage.ts
server/routes/contacts/add/success/successfullyAddedContactController.test.ts
server/routes/contacts/add/success/successfullyAddedContactController.ts
server/views/pages/contacts/common/addedContactSuccessfully.njk

Updates to the success page for new and existing contact journeys

PRC-529: Success page updates

---

integration_tests/e2e/editAddress.cy.ts
server/routes/contacts/manage/edit-contact-methods/editContactMethodsController.test.ts
server/views/pages/contacts/manage/contactDetails/details/editContactMethods.njk
server/views/partials/contactMethods/contactAddressCard.njk

PRC-278 Limit change links to previous addressesi to only change dates

---

integration_tests/pages/enterNamePage.ts
server/routes/contacts/add/enter-name/createContactEnterNameController.test.ts
server/routes/contacts/common/name/nameSchemas.ts
server/views/pages/contacts/add/new/enterName.njk

PRC-559 Create contact - enter name page

---

server/routes/contacts/manage/edit-restrictions/editRestrictionsController.test.ts
server/routes/restrictions/cancel/cancelAddRestrictionController.test.ts
server/routes/restrictions/check-answers/addRestrictionCheckAnswersController.test.ts
server/routes/restrictions/enter-restriction/enterNewRestrictionController.test.ts
server/routes/restrictions/success/successfullyAddedRestrictionController.test.ts
server/routes/restrictions/update-restriction/updateRestrictionController.test.ts

Add unit tests for Manage contact restriction pages' page title and back link

---

server/routes/contacts/add/contact-match/contactMatchController.test.ts
server/routes/contacts/add/contact-search/contactSearchController.test.ts
server/routes/contacts/add/employments/organisation-search/createContactOrganisationSearchController.ts
server/routes/contacts/manage/list/listContactsController.test.ts
server/routes/contacts/manage/update-employments/check-employer/checkEmployerController.test.ts
server/routes/contacts/manage/update-employments/delete-employment/deleteEmploymentController.test.ts
server/routes/contacts/manage/update-employments/employment-status/employmentStatusController.test.ts
server/routes/contacts/manage/update-employments/organisation-search/organisationSearchController.test.ts
server/routes/contacts/manage/update-employments/organisation-search/organisationSearchController.ts
server/routes/contacts/manage/update-employments/updateEmploymentsController.test.ts
server/views/pages/contacts/add/existing/match.njk

Update page titles for Edit professional information pages and list/search/match contact pages

---

assets/scss/local.scss
integration_tests/e2e/updatePrisonerContactEmployments.cy.ts
server/routes/contacts/manage/update-employments/updateEmploymentsController.test.ts
server/routes/contacts/manage/update-employments/updateEmploymentsController.ts
server/views/pages/contacts/manage/contactDetails/details/index.njk
server/views/pages/contacts/manage/employments/index.njk

Fix style on update-employment page and contact details page

---

integration_tests/e2e/createContacts.cy.ts
integration_tests/e2e/createContactsCheckAnswers.cy.ts
integration_tests/e2e/createContactsCheckAnswersChangeRelationship.cy.ts
server/routes/contacts/add/additional-info/addContactAdditionalInfoController.test.ts
server/views/pages/contacts/add/additionalInfo.njk

Should be "Comments on their relationship with [prisoner name]" but was contact name.

PRC-598: Fix additional info comments link

---

server/views/pages/contacts/manage/contactDetails/languageAndInterpreter.njk

Fix font on language auto-complete field

---

server/routes/contacts/add/check-answers/createContactCheckAnswersController.test.ts
server/views/pages/contacts/add/new/checkAnswers.njk

PRC-607 Fix edit phone numbers from CYA

---

server/views/pages/contacts/common/addedContactSuccessfully.njk
server/views/pages/contacts/manage/contactDetails/details/editContactMethods.njk
server/views/pages/contacts/manage/contactDetails/relationship/manageApprovedToVisit.njk
server/views/pages/contacts/manage/contactMethods/confirmDeletePhone.njk
server/views/pages/contacts/manage/contactSearch.njk
server/views/pages/contacts/manage/employments/checkEmployer/index.njk
server/views/pages/contacts/manage/employments/organisationSearch/index.njk
server/views/pages/contacts/manage/listContacts.njk

fixes:
list classes,
contact names on add contact success pages, and
phone number type label on delete phone confirmation page
PRC-608
PRC-610
PRC-611

misc ui fixes

---

server/routes/contacts/add/employments/organisation-search/createContactOrganisationSearchController.test.ts
server/routes/contacts/manage/update-employments/organisation-search/organisationSearchController.test.ts
server/views/pages/contacts/manage/employments/organisationSearch/index.njk

Add linebreak to check employer link

---

server/routes/contacts/manage/edit-contact-methods/editContactMethodsController.test.ts
server/utils/sortAddress.test.ts
server/utils/sortAddress.ts
server/views/pages/contacts/manage/contactDetails/details/editContactMethods.njk
server/views/partials/contactMethods/emailAddressesCard.njk

PRC-603 Update to Edit contact methods page

---

assets/js/all.js
assets/js/index.js
server/routes/contacts/add/employments/organisation-search/createContactOrganisationSearchController.test.ts
server/routes/contacts/add/employments/organisation-search/createContactOrganisationSearchController.ts
server/routes/contacts/manage/update-employments/organisation-search/organisationSearchController.ts
server/views/pages/contacts/manage/employments/organisationSearch/index.njk

PRC-596
1. starts with Start a search to view organisation records.
2. on changing page or sorting, move to top pagination anchor instead of moving to the top of the page
3. when empty search term is submitted, shows No organisation records match your search.

PRC-596 Update search employer page

---

server/routes/contacts/manage/contact-details/contactDetailsController.test.ts
server/views/pages/contacts/manage/contactDetails/details/editRestrictions.njk
server/views/pages/contacts/manage/contactDetails/details/restrictionsTab.njk
server/views/partials/restrictionsTable.njk

Remove <hr> between relationship and global restrictions. Add missing middle names for contact.

PRC-673: Restrictions table fixes

---

integration_tests/e2e/addExistingContactAsAdmin.cy.ts
integration_tests/e2e/createNewContactAsAdmin.cy.ts
server/routes/contacts/add/success/successfullyAddedContactController.test.ts
server/routes/contacts/manage/manageContactsRoutes.ts
server/views/pages/contacts/common/addedContactSuccessfully.njk

Only authoriser should see restrictions info on add & link success page.

PRC-605: RBAC success page tweaks

---

integration_tests/e2e/listContactsAsAdmin.cy.ts
integration_tests/e2e/listContactsAsReadOnlyUser.cy.ts
integration_tests/e2e/signIn.cy.ts
integration_tests/pages/listContacts.ts
server/routes/contacts/manage/list/listContactsController.test.ts
server/views/pages/contacts/manage/listContacts.njk

Hide add & link contact buttons and the manage contact link from the list of contacts. Update tests to match

PRC-602: Read-only user styling

---

integration_tests/mockApis/organisationsApi.ts
server/@types/organisationsApi/index.d.ts
server/@types/organisationsApiClient/index.d.ts
server/data/organisationsApiClient.ts
server/routes/contacts/add/employments/organisation-search/createContactOrganisationSearchController.test.ts
server/routes/contacts/add/employments/organisation-search/createContactOrganisationSearchController.ts
server/routes/contacts/manage/update-employments/organisation-search/organisationSearchController.test.ts
server/routes/contacts/manage/update-employments/organisation-search/organisationSearchController.ts
server/services/organisationsService.ts

Org model has updates to the paged result types

PRC-587: Update org model

---

server/routes/contacts/manage/list/listContactsController.test.ts
server/routes/contacts/manage/list/listContactsController.ts

Limit all query params to known good values to prevent XSS attacks using query params for the contact list.

PRC-723: Prevent XSS on contact list

---

server/views/pages/contacts/manage/contactSearch.njk

Add instructions on how to perform advanced searches using NOMIS.

PRC-733: Update search placeholder text

---

server/routes/contacts/add/contact-search/contactSearchController.test.ts
server/routes/contacts/add/contact-search/contactSearchController.ts
server/routes/contacts/common/name/nameSchemas.ts

Match the backends validation of name inputs in search.

PRC-723: Validate search input

---

server/routes/contacts/manage/addresses/enter-address/addressLinesSchemas.test.ts
server/routes/contacts/manage/addresses/enter-address/addressLinesSchemas.ts

PRC-682: Update address lines errors

---

integration_tests/e2e/createContactGlobalRestriction.cy.ts
integration_tests/e2e/createPrisonerContactRestriction.cy.ts
integration_tests/e2e/manageContactsRestrictions.cy.ts
integration_tests/e2e/updateContactGlobalRestriction.cy.ts
integration_tests/e2e/updatePrisonerContactRestriction.cy.ts
integration_tests/pages/editRestrictionsPage.ts
server/routes/contacts/manage/edit-restrictions/editRestrictionsController.test.ts
server/routes/restrictions/success/successfullyAddedRestrictionController.test.ts
server/routes/restrictions/success/successfullyAddedRestrictionController.ts
server/views/pages/contacts/manage/contactDetails/details/editRestrictions.njk
server/views/pages/contacts/restrictions/success.njk

Some missing middle names and padding changes on edit restrictions pages.

PRC-689: Restrictions tweaks

---

integration_tests/mockApis/componentApi.ts
package-lock.json
server/routes/contacts/manage/list/listContactsController.test.ts
server/routes/contacts/manage/list/listContactsController.ts
server/utils/nunjucksSetup.ts
server/utils/utils.ts
server/views/partials/contactDetails/prisonerContactSummaryTable.njk

Update dob to age on contact list

---

server/routes/contacts/manage/edit-contact-methods/editContactMethodsController.test.ts
server/routes/contacts/manage/update-employments/updateEmploymentsController.test.ts
server/views/pages/contacts/manage/contactDetails/details/editContactMethods.njk
server/views/pages/contacts/manage/employments/index.njk

Add warning text to edit-contact-method and update-employment pages

---

server/utils/announcement.ts
server/utils/announcements.test.ts

Add expandable warning banner at the top of contact list
Test evidence:
Open
Closed

PRC-873 : Add expandable warning banner at the top of contact list

---

server/routes/contacts/manage/contact-details/contactDetailsController.test.ts
server/views/pages/contacts/manage/contactDetails/details/restrictionsTab.njk

PRC-898 : Point users back to NOMIS to see Prisoner Restrictions

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

Revert "PRC-897 : On 26/08/25, remove the alert banner from DPS for HMP Leeds (#549)"

Revert "PRC-897 : On 26/08/25, remove the alert banner from DPS for HMP Leeds (#549)"

---

server/routes/contacts/manage/list/listContactsController.test.ts
server/utils/announcement.ts
server/utils/announcements.test.ts

PRC-945 : fix typo - SharePoint
